from app.crud.crud_persona import persona
from app.crud.crud_usuario import usuario
from app.crud.crud_rol import rol
from app.crud.crud_rol_usuario import rol_usuario
from app.crud.crud_dispositivo_usuario import dispositivo_usuario
from app.crud.crud_sesion import sesion
from app.crud.crud_vehiculo import vehiculo
from app.crud.crud_rol_permiso import rol_permiso
from app.crud.crud_permiso import permiso