"""Add constraint a vehiculo

Revision ID: 39c3768b46a3
Revises: d178cc6d9fb9
Create Date: 2026-04-11 23:46:29.054344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c3768b46a3'
down_revision: Union[str, Sequence[str], None] = 'd178cc6d9fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
