"""Add unique constraint to taller

Revision ID: 47c92620ad47
Revises: bca43af41020
Create Date: 2026-04-18 06:55:53.261002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c92620ad47'
down_revision: Union[str, Sequence[str], None] = 'bca43af41020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dispositivo_usuario_id'), 'dispositivo_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_permiso_id'), 'permiso', ['id'], unique=False)
    op.drop_index(op.f('uq_persona_ci_complemento'), table_name='persona', postgresql_where='(ci IS NOT NULL)')
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.drop_index(op.f('uq_rol_usuario_con_taller'), table_name='rol_usuario', postgresql_where='(id_taller IS NOT NULL)')
    op.drop_index(op.f('uq_rol_usuario_sin_taller'), table_name='rol_usuario', postgresql_where='(id_taller IS NULL)')
    op.create_index(op.f('ix_rol_usuario_id'), 'rol_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_sesion_id'), 'sesion', ['id'], unique=False)
    op.create_index('idx_solicitud_afiliacion_ubicacion', 'solicitud_afiliacion', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_solicitud_afiliacion_id'), 'solicitud_afiliacion', ['id'], unique=False)
    op.create_index('idx_taller_ubicacion', 'taller', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_taller_id'), 'taller', ['id'], unique=False)
    op.create_unique_constraint(None, 'taller', ['nombre'])
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculo_id'), 'vehiculo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculo_id'), table_name='vehiculo')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_constraint(None, 'taller', type_='unique')
    op.drop_index(op.f('ix_taller_id'), table_name='taller')
    op.drop_index('idx_taller_ubicacion', table_name='taller', postgresql_using='gist')
    op.drop_index(op.f('ix_solicitud_afiliacion_id'), table_name='solicitud_afiliacion')
    op.drop_index('idx_solicitud_afiliacion_ubicacion', table_name='solicitud_afiliacion', postgresql_using='gist')
    op.drop_index(op.f('ix_sesion_id'), table_name='sesion')
    op.drop_index(op.f('ix_rol_usuario_id'), table_name='rol_usuario')
    op.create_index(op.f('uq_rol_usuario_sin_taller'), 'rol_usuario', ['id_usuario', 'id_rol'], unique=True, postgresql_where='(id_taller IS NULL)')
    op.create_index(op.f('uq_rol_usuario_con_taller'), 'rol_usuario', ['id_usuario', 'id_rol', 'id_taller'], unique=True, postgresql_where='(id_taller IS NOT NULL)')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.create_index(op.f('uq_persona_ci_complemento'), 'persona', ['ci', sa.literal_column("COALESCE(complemento, ''::character varying)")], unique=True, postgresql_where='(ci IS NOT NULL)')
    op.drop_index(op.f('ix_permiso_id'), table_name='permiso')
    op.drop_index(op.f('ix_dispositivo_usuario_id'), table_name='dispositivo_usuario')
    # ### end Alembic commands ###
