"""Add constraint a vehiculo ahora si

Revision ID: 4aa9dd987f18
Revises: 39c3768b46a3
Create Date: 2026-04-11 23:47:39.858863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa9dd987f18'
down_revision: Union[str, Sequence[str], None] = '39c3768b46a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
