"""Add constraint a vehiculo ahora si2

Revision ID: 5389e0a50adf
Revises: 4aa9dd987f18
Create Date: 2026-04-11 23:52:43.086202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5389e0a50adf'
down_revision: Union[str, Sequence[str], None] = '4aa9dd987f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
