"""todo desde cero

Revision ID: 5bec391f0e9a
Revises: 92b44d9acc40
Create Date: 2026-04-21 22:32:35.650462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '5bec391f0e9a'
down_revision: Union[str, Sequence[str], None] = '92b44d9acc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_afiliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_revision', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estadosolicitudafiliacion'), nullable=False),
    sa.Column('comentario_revision', sa.Text(), nullable=True),
    sa.Column('id_usuario_solicita', sa.Integer(), nullable=False),
    sa.Column('id_usuario_revisa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_revisa'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario_solicita'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_afiliacion_id'), 'solicitud_afiliacion', ['id'], unique=False)
    op.create_table('solicitud_diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'diagnosticada', 'cancelada', 'error', name='estadosolicituddiagnostico'), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_diagnostico_id'), 'solicitud_diagnostico', ['id'], unique=False)
    op.create_table('taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('url_web', sa.Text(), nullable=True),
    sa.Column('puntos', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', name='estadotaller'), nullable=False),
    sa.Column('id_solicitud_afiliacion', sa.Integer(), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='check_horario'),
    sa.CheckConstraint('puntos >= 0 AND puntos <= 5', name='check_puntos'),
    sa.ForeignKeyConstraint(['id_solicitud_afiliacion'], ['solicitud_afiliacion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitud_afiliacion'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_taller_id'), 'taller', ['id'], unique=False)
    op.create_foreign_key(None, 'diagnostico', 'solicitud_diagnostico', ['id_solicitud_diagnostico'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'empleado', 'taller', ['id_taller'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'evidencia', 'solicitud_diagnostico', ['id_solicitud_diagnostico'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rol_usuario', 'taller', ['id_taller'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vehiculo_taller', 'taller', ['id_taller'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehiculo_taller', type_='foreignkey')
    op.drop_constraint(None, 'rol_usuario', type_='foreignkey')
    op.drop_constraint(None, 'evidencia', type_='foreignkey')
    op.drop_constraint(None, 'empleado', type_='foreignkey')
    op.drop_constraint(None, 'diagnostico', type_='foreignkey')
    op.drop_index(op.f('ix_taller_id'), table_name='taller')
    op.drop_table('taller')
    op.drop_index(op.f('ix_solicitud_diagnostico_id'), table_name='solicitud_diagnostico')
    op.drop_table('solicitud_diagnostico')
    op.drop_index(op.f('ix_solicitud_afiliacion_id'), table_name='solicitud_afiliacion')
    op.drop_table('solicitud_afiliacion')
    # ### end Alembic commands ###
