"""add_factura_table

Revision ID: 67a2acf835af
Revises: b84edaf038a9
Create Date: 2026-04-26 16:08:35.352792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a2acf835af'
down_revision: Union[str, Sequence[str], None] = 'b84edaf038a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('comision', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('liquido_taller', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sa.Enum('pendiente', 'pagado', 'fallido', 'reembolsado', name='estadopago'), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('id_pasarela', sa.String(length=255), nullable=True),
    sa.Column('url_qr', sa.String(length=1000), nullable=True),
    sa.Column('fecha_emision', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_pago', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_id'), 'factura', ['id'], unique=False)
    op.create_index(op.f('ix_factura_id_servicio'), 'factura', ['id_servicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_factura_id_servicio'), table_name='factura')
    op.drop_index(op.f('ix_factura_id'), table_name='factura')
    op.drop_table('factura')
    # ### end Alembic commands ###
