"""add especialidad

Revision ID: 83e95fcbc7dd
Revises: ce4b99de58e0
Create Date: 2026-04-18 16:00:30.973803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e95fcbc7dd'
down_revision: Union[str, Sequence[str], None] = 'ce4b99de58e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidad_id'), 'especialidad', ['id'], unique=False)
    op.create_table('tecnico_especialidad',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_empleado', 'id_especialidad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tecnico_especialidad')
    op.drop_index(op.f('ix_especialidad_id'), table_name='especialidad')
    op.drop_table('especialidad')
    # ### end Alembic commands ###
