"""atributo eliminado de categoria_incidente

Revision ID: 92b44d9acc40
Revises: cce78ae636c5
Create Date: 2026-04-21 19:40:53.394692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b44d9acc40'
down_revision: Union[str, Sequence[str], None] = 'cce78ae636c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
import geoalchemy2


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categoria_incidente_id'), 'categoria_incidente', ['id'], unique=False)
    op.create_table('tipo_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('prioridad', sa.SmallInteger(), nullable=False),
    sa.Column('requiere_remolque', sa.Boolean(), nullable=False),
    sa.Column('id_categoria_incidente', sa.Integer(), nullable=True),
    sa.CheckConstraint('prioridad BETWEEN 1 AND 5', name='check_prioridad_tipo_incidente'),
    sa.ForeignKeyConstraint(['id_categoria_incidente'], ['categoria_incidente.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concepto')
    )
    op.create_index(op.f('ix_tipo_incidente_id'), 'tipo_incidente', ['id'], unique=False)
    op.create_table('solicitud_diagnostico',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('estado', sa.Enum('pendiente', 'diagnosticada', 'cancelada', 'error', name='estadosolicituddiagnostico'), nullable=False),
        sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
        sa.Column('id_persona', sa.Integer(), nullable=False),
        sa.Column('id_vehiculo', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    # crear índice espacial solo si no existe (evita error DuplicateTable)
    bind = op.get_bind()
    exists = bind.execute(sa.text("SELECT to_regclass('public.idx_solicitud_diagnostico_ubicacion')")).scalar()
    if not exists:
        op.create_index('idx_solicitud_diagnostico_ubicacion', 'solicitud_diagnostico', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_solicitud_diagnostico_id'), 'solicitud_diagnostico', ['id'], unique=False)
    op.create_table('diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_confianza', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_solicitud_diagnostico', sa.Integer(), nullable=False),
    sa.CheckConstraint('nivel_confianza >= 0 AND nivel_confianza <= 1', name='check_nivel_confianza_diagnostico'),
    sa.ForeignKeyConstraint(['id_solicitud_diagnostico'], ['solicitud_diagnostico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitud_diagnostico')
    )
    op.create_index(op.f('ix_diagnostico_id'), 'diagnostico', ['id'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('audio', 'imagen', name='tipoevidencia'), nullable=False),
    sa.Column('id_solicitud_diagnostico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud_diagnostico'], ['solicitud_diagnostico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencia_id'), 'evidencia', ['id'], unique=False)
    op.create_table('incidente',
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('id_tipo_incidente', sa.Integer(), nullable=False),
    sa.Column('sugerido_por', sa.Enum('ia', 'conductor', name='sugeridopor'), nullable=False),
    sa.Column('nivel_confianza', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.CheckConstraint('nivel_confianza >= 0 AND nivel_confianza <= 1', name='check_nivel_confianza_incidente'),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnostico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_incidente'], ['tipo_incidente.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_diagnostico', 'id_tipo_incidente')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidente')
    op.drop_index(op.f('ix_evidencia_id'), table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index(op.f('ix_diagnostico_id'), table_name='diagnostico')
    op.drop_table('diagnostico')
    bind = op.get_bind()
    bind.execute(sa.text("DROP INDEX IF EXISTS public.idx_solicitud_diagnostico_ubicacion"))
    op.drop_index(op.f('ix_solicitud_diagnostico_id'), table_name='solicitud_diagnostico')
    op.drop_table('solicitud_diagnostico')
    op.drop_index(op.f('ix_tipo_incidente_id'), table_name='tipo_incidente')
    op.drop_table('tipo_incidente')
    op.drop_index(op.f('ix_categoria_incidente_id'), table_name='categoria_incidente')
    op.drop_table('categoria_incidente')
    # ### end Alembic commands ###
