"""add_cu13_cu14_tables

Revision ID: b84edaf038a9
Revises: abc123update
Create Date: 2026-04-26 14:46:12.816061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84edaf038a9'
down_revision: Union[str, Sequence[str], None] = 'abc123update'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_estados_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('creado', 'tecnico_asignado', 'en_camino', 'en_lugar', 'en_atencion', 'finalizado', 'cancelado', name='estadohistorial'), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tiempo_desde_anterior', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_servicio_id'), 'historial_estados_servicio', ['id'], unique=False)
    op.create_index(op.f('ix_historial_estados_servicio_id_servicio'), 'historial_estados_servicio', ['id_servicio'], unique=False)
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_remitente', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tiempo', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_remitente'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensaje_id'), 'mensaje', ['id'], unique=False)
    op.create_index(op.f('ix_mensaje_id_servicio'), 'mensaje', ['id_servicio'], unique=False)
    op.create_table('metrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('tiempo_respuesta', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_llegada', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_resolucion', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrica_id'), 'metrica', ['id'], unique=False)
    op.create_index(op.f('ix_metrica_id_servicio'), 'metrica', ['id_servicio'], unique=True)
    op.create_table('ubicacion_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitud', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_servicio', 'id_empleado', name='uq_ubicacion_tecnico_servicio')
    )
    op.create_index(op.f('ix_ubicacion_tecnico_id'), 'ubicacion_tecnico', ['id'], unique=False)
    op.create_index(op.f('ix_ubicacion_tecnico_id_servicio'), 'ubicacion_tecnico', ['id_servicio'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_ubicacion_tecnico_id_servicio'), table_name='ubicacion_tecnico')
    op.drop_index(op.f('ix_ubicacion_tecnico_id'), table_name='ubicacion_tecnico')
    op.drop_table('ubicacion_tecnico')
    op.drop_index(op.f('ix_metrica_id_servicio'), table_name='metrica')
    op.drop_index(op.f('ix_metrica_id'), table_name='metrica')
    op.drop_table('metrica')
    op.drop_index(op.f('ix_mensaje_id_servicio'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_id'), table_name='mensaje')
    op.drop_table('mensaje')
    op.drop_index(op.f('ix_historial_estados_servicio_id_servicio'), table_name='historial_estados_servicio')
    op.drop_index(op.f('ix_historial_estados_servicio_id'), table_name='historial_estados_servicio')
    op.drop_table('historial_estados_servicio')
    # ### end Alembic commands ###
