"""add vehiculo_taller

Revision ID: cce78ae636c5
Revises: 83e95fcbc7dd
Create Date: 2026-04-18 18:03:10.605187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce78ae636c5'
down_revision: Union[str, Sequence[str], None] = '83e95fcbc7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('servicio', 'remolque', 'otro', name='tipovehiculotaller'), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'en_servicio', 'en_mantenimiento', 'inactivo', name='estadovehiculotaller'), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.CheckConstraint('anio >= 1900 AND anio <= 2100', name='check_anio_vehiculo_taller'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculo_taller_id'), 'vehiculo_taller', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculo_taller_id'), table_name='vehiculo_taller')
    op.drop_table('vehiculo_taller')
    # ### end Alembic commands ###
