"""Add empleado table and enum

Revision ID: ce4b99de58e0
Revises: 47c92620ad47
Create Date: 2026-04-18 09:50:36.148605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4b99de58e0'
down_revision: Union[str, Sequence[str], None] = '47c92620ad47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_salida', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'disponible', 'en_servicio', 'suspendido', name='estadoempleado'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.CheckConstraint('fecha_salida IS NULL OR fecha_salida >= fecha_ingreso', name='chk_fechas_empleado'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleado_id'), 'empleado', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empleado_id'), table_name='empleado')
    op.drop_table('empleado')
    # ### end Alembic commands ###
