"""Add vehiculo table and enum

Revision ID: d178cc6d9fb9
Revises: ff09a8f3e488
Create Date: 2026-04-11 23:32:25.958176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd178cc6d9fb9'
down_revision: Union[str, Sequence[str], None] = 'ff09a8f3e488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('auto', 'camioneta', 'moto', 'camion', 'microbus', 'otro', name='tipovehiculo'), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculo_id'), 'vehiculo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculo_id'), table_name='vehiculo')
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
