"""ciclo2

Revision ID: e6e251c05713
Revises: 059e870b0e19
Create Date: 2026-04-17 11:14:53.404895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e6e251c05713'
down_revision: Union[str, Sequence[str], None] = '059e870b0e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categoria_incidente_id'), 'categoria_incidente', ['id'], unique=False)
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidad_id'), 'especialidad', ['id'], unique=False)
    op.create_table('tipo_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', 'critica', 'emergencia', name='prioridadincidente'), nullable=False),
    sa.Column('requiere_remolque', sa.Boolean(), nullable=True),
    sa.Column('id_categoria_incidente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria_incidente'], ['categoria_incidente.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_incidente_id'), 'tipo_incidente', ['id'], unique=False)
    op.create_table('incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sugerido_por', sa.Enum('ia', 'usuario', 'admin', name='sugeridopor'), nullable=False),
    sa.Column('nivel_confianza', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_tipo_incidente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_incidente'], ['tipo_incidente.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidente_id'), 'incidente', ['id'], unique=False)
    op.create_table('solicitud_diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'procesando', 'completado', 'fallido', 'cancelado', name='estadosolicituddiagnostico'), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_incidente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_solicitud_diagnostico_ubicacion', 'solicitud_diagnostico', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_solicitud_diagnostico_id'), 'solicitud_diagnostico', ['id'], unique=False)
    op.create_table('diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('nivel_confianza', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_diagnostico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostico_id'), 'diagnostico', ['id'], unique=False)
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', 'ocupado', 'vacaciones', name='estadoempleado'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_empleado_id'), 'empleado', ['id'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('audio', 'imagen', 'texto', name='tipoevidencia'), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_diagnostico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencia_id'), 'evidencia', ['id'], unique=False)
    op.create_table('solicitud_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('ofertada', 'aceptada', 'rechazada', name='estadosolicitudservicio'), nullable=False),
    sa.Column('costo_estimado', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.Column('id_solicitud_diagnostico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud_diagnostico'], ['solicitud_diagnostico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_solicitud_servicio_ubicacion', 'solicitud_servicio', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_solicitud_servicio_id'), 'solicitud_servicio', ['id'], unique=False)
    op.create_table('vehiculo_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tipo', postgresql.ENUM('auto', 'camioneta', 'moto', 'camion', 'microbus', 'otro', name='tipovehiculo', create_type=False), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'en_servicio', 'mantenimiento', 'inactivo', name='estadovehiculotaller'), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.CheckConstraint('anio >= 1900 AND anio <= 2100', name='check_anio_vehiculo_taller'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculo_taller_id'), 'vehiculo_taller', ['id'], unique=False)
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('asignado', 'en_camino', 'en_curso', 'finalizado', 'cancelado', name='estadoservicio'), nullable=False),
    sa.Column('id_solicitud_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud_servicio'], ['solicitud_servicio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitud_servicio')
    )
    op.create_index(op.f('ix_servicio_id'), 'servicio', ['id'], unique=False)
    op.create_table('tecnico_especialidad',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_empleado', 'id_especialidad')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('comision', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('liquido_taller', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sa.Enum('pendiente', 'pagado', 'fallido', name='estadopago'), nullable=False),
    sa.Column('id_pasarela', sa.String(length=255), nullable=True),
    sa.Column('url_qr', sa.String(length=255), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_servicio')
    )
    op.create_index(op.f('ix_factura_id'), 'factura', ['id'], unique=False)
    op.create_table('historial_estados_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('asignado', 'en_camino', 'en_curso', 'finalizado', 'cancelado', name='estadoservicio'), nullable=False),
    sa.Column('tiempo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_servicio_id'), 'historial_estados_servicio', ['id'], unique=False)
    op.create_table('servicio_tecnico',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_servicio', 'id_empleado')
    )
    op.create_table('servicio_vehiculo',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo_taller', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vehiculo_taller'], ['vehiculo_taller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_servicio', 'id_vehiculo_taller')
    )
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.CheckConstraint('puntos >= 1 AND puntos <= 5', name='check_puntos_valoracion'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_servicio')
    )
    op.create_index(op.f('ix_valoracion_id'), 'valoracion', ['id'], unique=False)
    op.drop_index(op.f('uq_persona_ci_complemento'), table_name='persona', postgresql_where='(ci IS NOT NULL)')
    op.drop_index(op.f('uq_rol_usuario_con_taller'), table_name='rol_usuario', postgresql_where='(id_taller IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_rol_usuario_con_taller'), 'rol_usuario', ['id_usuario', 'id_rol', 'id_taller'], unique=True, postgresql_where='(id_taller IS NOT NULL)')
    op.create_index(op.f('uq_persona_ci_complemento'), 'persona', ['ci', sa.literal_column("COALESCE(complemento, ''::character varying)")], unique=True, postgresql_where='(ci IS NOT NULL)')
    op.drop_index(op.f('ix_valoracion_id'), table_name='valoracion')
    op.drop_table('valoracion')
    op.drop_table('servicio_vehiculo')
    op.drop_table('servicio_tecnico')
    op.drop_index(op.f('ix_historial_estados_servicio_id'), table_name='historial_estados_servicio')
    op.drop_table('historial_estados_servicio')
    op.drop_index(op.f('ix_factura_id'), table_name='factura')
    op.drop_table('factura')
    op.drop_table('tecnico_especialidad')
    op.drop_index(op.f('ix_servicio_id'), table_name='servicio')
    op.drop_table('servicio')
    op.drop_index(op.f('ix_vehiculo_taller_id'), table_name='vehiculo_taller')
    op.drop_table('vehiculo_taller')
    op.drop_index(op.f('ix_solicitud_servicio_id'), table_name='solicitud_servicio')
    # op.drop_index('idx_solicitud_servicio_ubicacion', table_name='solicitud_servicio', postgresql_using='gist')
    op.drop_table('solicitud_servicio')
    op.drop_index(op.f('ix_evidencia_id'), table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index(op.f('ix_empleado_id'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_index(op.f('ix_diagnostico_id'), table_name='diagnostico')
    op.drop_table('diagnostico')
    op.drop_index(op.f('ix_solicitud_diagnostico_id'), table_name='solicitud_diagnostico')
    # op.drop_index('idx_solicitud_diagnostico_ubicacion', table_name='solicitud_diagnostico', postgresql_using='gist')
    op.drop_table('solicitud_diagnostico')
    op.drop_index(op.f('ix_incidente_id'), table_name='incidente')
    op.drop_table('incidente')
    op.drop_index(op.f('ix_tipo_incidente_id'), table_name='tipo_incidente')
    op.drop_table('tipo_incidente')
    op.drop_index(op.f('ix_especialidad_id'), table_name='especialidad')
    op.drop_table('especialidad')
    op.drop_index(op.f('ix_categoria_incidente_id'), table_name='categoria_incidente')
    op.drop_table('categoria_incidente')
    # ### end Alembic commands ###
