"""Initial tables

Revision ID: f5cf0b63876c
Revises: 
Create Date: 2026-04-11 12:13:34.171464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cf0b63876c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dispositivo_usuario_id'), 'dispositivo_usuario', ['id'], unique=False)
    op.drop_index(op.f('uq_persona_ci_complemento'), table_name='persona', postgresql_where='(ci IS NOT NULL)')
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_index(op.f('ix_sesion_id'), 'sesion', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_sesion_id'), table_name='sesion')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.create_index(op.f('uq_persona_ci_complemento'), 'persona', ['ci', sa.literal_column("COALESCE(complemento, ''::character varying)")], unique=True, postgresql_where='(ci IS NOT NULL)')
    op.drop_index(op.f('ix_dispositivo_usuario_id'), table_name='dispositivo_usuario')
    # ### end Alembic commands ###
